export enum LuaTiErrorCode {
    Unspecified,
    NoSymbol,
    OverwriteSymbol,
    DuplicateDeclarationAsParameter,
    CallUndefinedSymbol,
    CannotAssignUndefinedSymbol,
    CannotAccessCompilerOptionsOfRootFile,
    UnknownAnnotationDeclaration,
    AnnotationTypeMismatch,
    AnnotationError,
    NoLabel,
    NoStringCall,
    NoTableCall,
    PropertyXDoesNotExistOnTypeY,
}